---
# - hosts: all
#   tasks:
#   # this task takes a long time.
# ---
# - hosts: all
#   become: true
#   tasks:
#   - name: Setup Docker
#     # become: true
#     import_playbook: docker.yml

- name: Setup Docker
  import_playbook: docker.yml

- hosts: all
  tasks:
  - name: Add to bashrc to default in share folder.
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'cd /share'
      insertbefore: BOF

- hosts: all
  tasks:
  - name: Add to bashrc to change default editor to vim.
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export EDITOR=vim'
      insertbefore: BOF

