---
# - hosts: all
#   tasks:
#   # this task takes a long time.
# ---
# - hosts: all
#   become: true
#   tasks:
#   - name: Setup Docker
#     # become: true
#     import_playbook: docker.yml

- name: Setup Docker
  import_playbook: docker.yml


